name: Release Go Binaries

permissions:
  contents: write
  packages: write

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: Windows
    steps:
      - uses: actions/checkout@v3

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          md5sum: false
          build_flags: -v
          binary_name: clipper
          extra_files: LICENSE.md README.md
          ldflags: -X "main.buildVersion=${{ env.APP_VERSION }}" -X "main.buildCommit=${{ github.sha }}" -X main.buildTime=$(date +%s) -X main.buildArch=${{ matrix.goos }} -X main.buildOS=${{ matrix.goarch }}"
