name: Release Go Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: Windows
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_flags: -v
          ldflags: -X "main.version=${{ env.APP_VERSION }}" -X "main.commit=${{ github.sha }}"